#!/bin/sh

printUsage() 
{
	echo "      Usage: oss [-u user] [-p port] [-i identify_key] [-l ip_list_file] [ip1 ip2 ... ipn]"
	echo "      eg: oss test12 test13"
	echo "      eg: oss -l ip_list_file"
	exit 2
}



#load config file
ossPath=`which oss`
ossDirPath=`dirname ${ossPath}`
configFilePath="${ossDirPath}/config.sh"

if [ -e ${configFilePath} ]
then
	source ${configFilePath}
fi


#parse argument
has_specify_ip_list=0

while getopts "i:p:u:l:" option
do
	case $option in
		i)
			key=$OPTARG;;
    		p)
			port=$OPTARG;;
    		u)
			user=$OPTARG;;
    		l)
			ip_list_file=$OPTARG
			;;
		[?])
			printUsage
			;;
	esac
done


if [ -n "$ip_list_file" ]
then
	hosts=`cat ${ip_list_file}`
else
	hosts=$*
fi

if [ -z "${hosts}" ]
then
	printUsage
fi


if [ -n "${port}" ]
then
	sshStringPrefix="${sshStringPrefix} -p ${port}";
fi

if [ -n "${key}" ]
then
	sshStringPrefix="${sshStringPrefix} -i ${key}";
fi

if [ -n "${user}" ]
then
	sshStringPrefix="${sshStringPrefix} ${user}@";
fi


#construct tumux window
tmux new-session -d -s localhost

i=0
hasCloseFirstPane=false
for host in ${hosts}
do
	#a tmux window could contain 6 pane at most
	#so close the first incase output 'create pane failed: pane too small'
	if [ 1 -eq ${i} ]
	then
		tmux kill-pane -t 0
		hasCloseFirstPane=true
	fi
	
	sshString="ssh ${sshStringPrefix}${host}"
	tmux split-window -h "${sshString}"
	i=$((i+1))
done

#if did not kill first pane, kill it here
if [ false = ${hasCloseFirstPane} ]
then
	tmux kill-pane -t 0
fi

tmux select-pane -t 0
tmux select-layout tiled
tmux set-window-option synchronize-panes on
 
tmux -2 attach-session -t localhost


